---
- hosts: aws_ec2
  become: true
  become_user: root
  gather_facts: false
  # vars_prompt:
  #    name: DOCKER_REG_PASSWORD
  #    prompt: enter the pasword
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: Install docker python modules
    pip: name=docker state=present executable=pip3
  - name: Install docker compose python modules
    pip: name=docker-compose state=present executable=pip3
  - name: Install urllib3 with compatible version
    pip: name=urllib3<2.0 state=present
  - name: docker login
    docker_login: registry_url=https://index.docker.io/v1/ username=devopstrainer password={{DOCKER_REG_PASSWORD}}
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.21.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: +x
  # - name: copy docker-compose file from ACM to targets
  #   copy: src=/home/ec2-user/docker-compose.yml dest=/home/ec2-user
  - name: Run the docker-compose
    docker_compose:
      project_name: PHP_DB
      definition:
          version: "3"
          services:
              web:
                image: "{{ DOCKER_IMAGE }}"
                ports:
                - "8001-8002:80"
                deploy:
                    replicas: 2
                depends_on:
                - mysql
              mysql:
                image: devopstrainer/java-mvn-privaterepos:mysql
                volumes:
                - db_data:/var/lib/mysql
                environment:
                  MYSQL_ROOT_PASSWORD: password
                  MYSQL_DATABASE: mydatabase
          volumes:
            db_data: {}

 