version: "3"
services:
    web:
      image: yshevkar/phprepo:v1$BUILD_NUMBER
      ports:
      - "8001:80"
      depends_on:
      - mysql
    mysql:
      image: yshevkar/sqlrepo:v1
      volumes:
      - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
volumes:
   db_data: {}